# Generated by Django 2.0.5 on 2018-05-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('clave_ct', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Clave del Centro de trabajo')),
                ('nombre_ct', models.CharField(default='', max_length=25, verbose_name='Nombre de la Escuela')),
                ('nivel_educ', models.CharField(choices=[('01', 'Educ. Inicial'), ('02', 'Educ. Preescolar'), ('03', 'Educ. Preescolar Indigena'), ('04', 'Educ. Primaria'), ('05', 'Educ. Primaria Indigena'), ('06', 'Educ. Secundaria'), ('07', 'Educ. Telesecundaria'), ('08', 'Educ. Secundaria Técnica'), ('09', 'Educ. Especial'), ('10', 'Educ. Media Superior'), ('11', 'Educ. Superior')], max_length=2, verbose_name='Nivel Educativo')),
                ('turno', models.CharField(choices=[('100', 'Matutino'), ('120', 'Matutino y Vespertino'), ('200', 'Vespertino'), ('600', 'Complementario'), ('700', 'Continuo (Jornada amplía)')], default='100', max_length=3, verbose_name='Turno')),
                ('zona_esc', models.CharField(default='', max_length=2, verbose_name='Zona Escolar')),
                ('sector', models.CharField(default='', max_length=2, verbose_name='Sector Educativo')),
                ('dom_calle', models.CharField(default='', max_length=50, verbose_name='Calle y número')),
                ('cp', models.CharField(default='', max_length=5, verbose_name='Codigo Postal')),
                ('municipio', models.CharField(choices=[('001', 'Amealco de Bonfil'), ('002', 'Pinal de Amoles'), ('003', 'Arroyo Seco'), ('004', 'Caderyta'), ('005', 'Colon'), ('007', 'Ezequiel Montes'), ('008', 'Huimilpan'), ('009', 'Jalpan de Serra'), ('010', 'Landa de Matamoros'), ('011', 'El Maqués'), ('012', 'Pedro Escobedo'), ('013', 'Peñamiller'), ('014', 'Querétaro de Arteaga'), ('015', 'San Joaquín'), ('016', 'San Juan del Rio'), ('017', 'Tequisquiapan'), ('018', 'Toliman')], max_length=3, verbose_name='Municipio')),
                ('estado', models.CharField(choices=[('01', 'Aguascalientes'), ('02', 'Baja California'), ('03', 'Baja California Sur'), ('04', 'Campeche'), ('05', 'Coahuila de Zaragoza'), ('06', 'Colima'), ('07', 'Chiapas'), ('08', 'Chihuahua'), ('09', 'Ciudad de México'), ('10', 'Durango'), ('11', 'Guanajuato'), ('12', 'Guerrero'), ('13', 'Hidalgo'), ('14', 'Jalisco'), ('15', 'México'), ('16', 'Michoacán de Ocampo'), ('17', 'Morelos'), ('18', 'Nayarit'), ('19', 'Nuevo León'), ('20', 'Oaxaca'), ('21', 'Puebla'), ('22', 'Querétaro'), ('23', 'Quintana Roo'), ('24', 'San Luis Potosí'), ('25', 'Sinaloa'), ('26', 'Sonora'), ('27', 'Tabasco'), ('28', 'Tamaulipas'), ('29', 'Tlaxcala'), ('30', 'Veracruz de Ignacio de la Llave'), ('31', 'Yucatán'), ('32', 'Zacatecas')], default='22', max_length=2, verbose_name='Estado')),
            ],
        ),
    ]
