# Generated by Django 2.0.5 on 2018-05-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('apaterno', models.CharField(default='', max_length=15, verbose_name='Apellido Paterno')),
                ('amaterno', models.CharField(default='', max_length=15, verbose_name='Apellido Materno')),
                ('nombre', models.CharField(default='', max_length=30, verbose_name='Nombre del Docente')),
                ('rfc', models.CharField(default='', max_length=13, verbose_name='RFC del docente')),
                ('curp', models.CharField(max_length=17, primary_key=True, serialize=False, verbose_name='Escriba su CURP')),
                ('edo_civil', models.CharField(choices=[('SOL', 'Soltero'), ('CAS', 'Casado'), ('UNI', 'Unión libre')], max_length=3, verbose_name='Estado Civil')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('dom_calle', models.CharField(default='', max_length=50, verbose_name='Calle y número')),
                ('colonia', models.CharField(default='', max_length=25, verbose_name='Colonia')),
                ('cp', models.CharField(default='', max_length=5, verbose_name='Codigo Postal')),
                ('localidad', models.CharField(default='', max_length=25, verbose_name='Localidad')),
                ('municipio', models.CharField(default='', max_length=25, verbose_name='Municipio')),
                ('tel_cel', models.CharField(default='', max_length=10, verbose_name='Telefono Celular')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
            ],
        ),
    ]
