# Generated by Django 2.0.5 on 2018-05-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionplazas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='curp_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionplazas.Evaluacion', verbose_name='CURP del docentes'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='curp_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiondocentes.Docente', verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='lista',
            field=models.IntegerField(verbose_name='Número de lista'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='motivobaja',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Motivo de la baja'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='prelacion',
            field=models.IntegerField(verbose_name='Orden prelación'),
        ),
    ]
