# Generated by Django 2.0.5 on 2018-05-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionplazas', '0002_auto_20180504_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='curp_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionplazas.Evaluacion', verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='suestado',
            field=models.CharField(choices=[('ASI', 'Asignado'), ('BAJ', 'Baja'), ('PAS', 'Para asignar')], max_length=3, verbose_name='Estado Evaluación'),
        ),
    ]
